# Generated by Django 5.0.1 on 2024-01-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='QR_image_url',
            new_name='qr_image_url',
        ),
    ]
